[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "~1.13.25"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "~0.8.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[prune]
  go-tests = true
  unused-packages = true
